export const PET_LIST_REQUEST = 'PET_LIST_REQUEST'
export const PET_LIST_SUCCESS = 'PET_LIST_SUCCESS'
export const PET_LIST_FAIL = 'PET_LIST_FAIL'

export const PET_DETAILS_REQUEST = 'PET_DETAILS_REQUEST'
export const PET_DETAILS_SUCCESS = 'PET_DETAILS_SUCCESS'
export const PET_DETAILS_FAIL = 'PET_DETAILS_FAIL'

export const MY_PET_LIST_REQUEST = 'MY_PET_LIST_REQUEST'
export const MY_PET_LIST_SUCCESS = 'MY_PET_LIST_SUCCESS'
export const MY_PET_LIST_FAIL = 'MY_PET_LIST_FAIL'

export const PET_DELETE_REQUEST = 'PET_DELETE_REQUEST'
export const PET_DELETE_SUCCESS = 'PET_DELETE_SUCCESS'
export const PET_DELETE_FAIL = 'PET_DELETE_FAIL'

export const PET_CREATE_REQUEST = 'PET_CREATE_REQUEST'
export const PET_CREATE_SUCCESS = 'PET_CREATE_SUCCESS'
export const PET_CREATE_FAIL = 'PET_CREATE_FAIL'
export const PET_CREATE_RESET = 'PET_CREATE_RESET'

export const PET_UPDATE_REQUEST = 'PET_UPDATE_REQUEST'
export const PET_UPDATE_SUCCESS = 'PET_UPDATE_SUCCESS'
export const PET_UPDATE_FAIL = 'PET_UPDATE_FAIL'
export const PET_UPDATE_RESET = 'PET_UPDATE_RESET'

export const PET_CREATE_REVIEW_REQUEST = 'PET_CREATE_REVIEW_REQUEST'
export const PET_CREATE_REVIEW_SUCCESS = 'PET_CREATE_REVIEW_SUCCESS'
export const PET_CREATE_REVIEW_FAIL = 'PET_CREATE_REVIEW_FAIL'
export const PET_CREATE_REVIEW_RESET = 'PET_UPDATE_RESET'

export const PET_TOP_REQUEST = 'PET_TOP_REQUEST'
export const PET_TOP_SUCCESS = 'PET_TOP_SUCCESS'
export const PET_TOP_FAIL = 'PET_TOP_FAIL'