export const REQUEST_CREATE_REQUEST = 'REQUEST_CREATE_REQUEST'
export const REQUEST_CREATE_SUCCESS = 'REQUEST_CREATE_SUCCESS'
export const REQUEST_CREATE_FAIL = 'REQUEST_CREATE_FAIL'

export const REQUEST_CREATE_RESET = 'REQUEST_CREATE_RESET'

export const REQUEST_DETAILS_REQUEST = 'REQUEST_DETAILS_REQUEST'
export const REQUEST_DETAILS_SUCCESS = 'REQUEST_DETAILS_SUCCESS'
export const REQUEST_DETAILS_FAIL = 'REQUEST_DETAILS_FAIL'

export const REQUEST_LIST_MY_REQUEST = 'REQUEST_LIST_MY_REQUEST'
export const REQUEST_LIST_MY_SUCCESS = 'REQUEST_LIST_MY_SUCCESS'
export const REQUEST_LIST_MY_FAIL = 'REQUEST_LIST_MY_FAIL'
export const REQUEST_LIST_MY_RESET = 'REQUEST_LIST_MY_RESET'

export const PET_REQUEST_LIST_MY_REQUEST = 'PET_REQUEST_LIST_MY_REQUEST'
export const PET_REQUEST_LIST_MY_SUCCESS = 'PET_REQUEST_LIST_MY_SUCCESS'
export const PET_REQUEST_LIST_MY_FAIL = 'PET_REQUEST_LIST_MY_FAIL'

export const REQUEST_LIST_REQUEST = 'REQUEST_LIST_REQUEST'
export const REQUEST_LIST_SUCCESS = 'REQUEST_LIST_SUCCESS'
export const REQUEST_LIST_FAIL = 'REQUEST_LIST_FAIL'

export const REQUEST_ACCEPT_REQUEST = 'REQUEST_ACCEPT_REQUEST'
export const REQUEST_ACCEPT_SUCCESS = 'REQUEST_ACCEPT_SUCCESS'
export const REQUEST_ACCEPT_FAIL = 'REQUEST_ACCEPT_FAIL'
export const REQUEST_ACCEPT_RESET = 'REQUEST_ACCEPT_RESET'